import type { AlertItem, DailyLog, Order, Project } from './types'

export const projects: Project[] = [
  {
    id: 'residencial-aurora',
    name: 'Residencial Aurora',
    location: 'Campinas, SP',
    manager: 'Marcos Oliveira',
    startDate: '2026-02-03',
    endDate: '2026-11-28',
    stage: 'Alvenaria',
    progress: 64,
    scheduleProgress: 68,
    invested: 1840000,
    marketValue: 2640000,
    spent: 1246000,
    budget: 1960000,
    status: 'No prazo',
    nextMilestone: 'Cobertura concluída',
    milestoneDate: '26 jul',
    team: 18,
  },
  {
    id: 'vila-serena',
    name: 'Vila Serena',
    location: 'Valinhos, SP',
    manager: 'Camila Torres',
    startDate: '2025-10-14',
    endDate: '2026-08-30',
    stage: 'Acabamentos',
    progress: 82,
    scheduleProgress: 88,
    invested: 970000,
    marketValue: 1460000,
    spent: 846000,
    budget: 1040000,
    status: 'Atenção',
    nextMilestone: 'Entrega da marcenaria',
    milestoneDate: '22 jul',
    team: 11,
  },
  {
    id: 'parque-das-flores',
    name: 'Parque das Flores',
    location: 'Jundiaí, SP',
    manager: 'André Martins',
    startDate: '2026-04-06',
    endDate: '2027-02-19',
    stage: 'Fundação',
    progress: 28,
    scheduleProgress: 36,
    invested: 1260000,
    marketValue: 2050000,
    spent: 514000,
    budget: 1580000,
    status: 'Atrasada',
    nextMilestone: 'Baldrame liberado',
    milestoneDate: '19 jul',
    team: 15,
  },
  {
    id: 'casa-horizonte',
    name: 'Casa Horizonte',
    location: 'Indaiatuba, SP',
    manager: 'Paulo Mendes',
    startDate: '2026-01-19',
    endDate: '2026-10-16',
    stage: 'Instalações',
    progress: 51,
    scheduleProgress: 50,
    invested: 720000,
    marketValue: 1120000,
    spent: 548000,
    budget: 860000,
    status: 'No prazo',
    nextMilestone: 'Teste hidráulico',
    milestoneDate: '29 jul',
    team: 9,
  },
]

export const alerts: AlertItem[] = [
  { id: 1, projectId: 'parque-das-flores', level: 'critical', title: 'Entrega sem baixa há 27h', description: '120 sacos de cimento · Pedido #1048', age: 'há 12 min' },
  { id: 2, projectId: 'vila-serena', level: 'warning', title: 'Estoque mínimo atingido', description: 'Argamassa ACIII · Curva A', age: 'há 38 min' },
  { id: 3, projectId: 'residencial-aurora', level: 'info', title: 'Cotação pronta para aprovação', description: 'Elétrica · economia potencial de R$ 4.280', age: 'há 1h' },
]

export const orders: Order[] = [
  { id: '#1052', projectId: 'residencial-aurora', item: 'Aço CA-50 · 780 kg', supplier: 'Aços Campinas', value: 6170, status: 'Cotado', date: '20 jul' },
  { id: '#1051', projectId: 'vila-serena', item: 'Porcelanato · 86 m²', supplier: 'Revest Lar', value: 9870, status: 'Aprovado', date: '20 jul' },
  { id: '#1050', projectId: 'casa-horizonte', item: 'Tubos e conexões', supplier: 'Hidrocenter', value: 3280, status: 'Em trânsito', date: '19 jul' },
  { id: '#1049', projectId: 'parque-das-flores', item: 'Areia média · 12 m³', supplier: 'Porto Areia', value: 2160, status: 'Pendente', date: '19 jul' },
]

export const dailyLogs: DailyLog[] = [
  {
    id: 'rdo-2026-07-20-aurora',
    projectId: 'residencial-aurora',
    date: '2026-07-20',
    weather: 'Ensolarado',
    temperature: 27,
    teamCount: 18,
    activities: ['Elevação da alvenaria do 2º pavimento', 'Passagem de eletrodutos nos quartos', 'Conferência de prumo das paredes'],
    notes: 'A frente leste avançou conforme o planejado. Materiais e equipe disponíveis durante todo o período.',
    occurrences: 'Nenhuma ocorrência de segurança registrada.',
    author: 'Marcos Oliveira',
    createdAt: '2026-07-20T17:42:00-03:00',
    photos: [
      { id: 'foto-a1', name: 'Alvenaria do 2º pavimento', theme: 'masonry' },
      { id: 'foto-a2', name: 'Conferência dos vãos', theme: 'structure' },
      { id: 'foto-a3', name: 'Passagem elétrica', theme: 'installation' },
    ],
  },
  {
    id: 'rdo-2026-07-19-aurora',
    projectId: 'residencial-aurora',
    date: '2026-07-19',
    weather: 'Parcialmente nublado',
    temperature: 24,
    teamCount: 16,
    activities: ['Montagem das vergas e contravergas', 'Recebimento e conferência de blocos cerâmicos'],
    notes: 'O recebimento foi conferido pelo encarregado e não apresentou divergências.',
    occurrences: 'A concretagem prevista para a manhã foi transferida para o período da tarde.',
    author: 'Marcos Oliveira',
    createdAt: '2026-07-19T18:05:00-03:00',
    photos: [
      { id: 'foto-a4', name: 'Vergas executadas', theme: 'structure' },
      { id: 'foto-a5', name: 'Material recebido', theme: 'masonry' },
    ],
  },
  {
    id: 'rdo-2026-07-20-vila',
    projectId: 'vila-serena',
    date: '2026-07-20',
    weather: 'Chuvoso',
    temperature: 20,
    teamCount: 11,
    activities: ['Assentamento de porcelanato da suíte', 'Instalação de louças do banheiro social'],
    notes: 'Serviços internos mantidos normalmente apesar da chuva.',
    occurrences: 'Entrega da marcenaria reagendada pelo fornecedor.',
    author: 'Camila Torres',
    createdAt: '2026-07-20T16:58:00-03:00',
    photos: [{ id: 'foto-v1', name: 'Porcelanato da suíte', theme: 'finishing' }],
  },
]
